version: "3.9"

# 실행하려는 컨테이너들 정의
services:
  backend:
    image: "jonghyeoknam/wit-backend:latest"
    #build: .
    container_name: wit-backend
    restart: always
    ports:
      - "8080:8080"
#    environment: # GitHub Secrets → SSH envs 로 넘길 예정
#      - MYSQLDB_USERNAME=${MYSQLDB_USERNAME}
#      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
#      - MYSQLDB_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    # my-db의 컨테이너가 생성되고 healthy 하다고 판단 될 때, 해당 컨테이너를 생성한다.
    depends_on:
      #      wit-db:
      #        condition: service_healthy
      redis_container:
        condition: service_healthy


  # 서비스명
  redis_container:
    # 사용할 이미지
    image: wit-redis:latest
    # 컨테이너명
    container_name: wit-redis
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    hostname: localhost
    ports:
      - 6380:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf